name: Build and Release Desktop App

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string
      release_notes:
        description: 'Release notes'
        required: false
        type: string
        default: ''

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build desktop app
      run: npm run build
      
    - name: Modify package.json to disable code signing completely
      run: |
        # Create a backup
        cp package.json package.json.backup
        
        # Use PowerShell to modify the JSON
        powershell -Command "
        $json = Get-Content 'package.json' | ConvertFrom-Json
        $json.build.forceCodeSigning = $false
        $json.build.win.sign = $false
        $json.build.win.verifyUpdateCodeSignature = $false
        $json.build.win.target = 'portable'
        $json.build.win.requestedExecutionLevel = 'asInvoker'
        $json | ConvertTo-Json -Depth 10 | Set-Content 'package.json'
        "
        
    - name: Build portable app (no code signing)
      run: |
        npx electron-builder --win --x64 --ia32
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: false
        
    - name: Restore package.json
      run: |
        cp package.json.backup package.json
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: desktop-app-build
        path: dist-electron/
        retention-days: 30
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ inputs.version }}
        name: BrokerNet Desktop v${{ inputs.version }}
        body: |
          ## What's New
          ${{ inputs.release_notes || 'Bug fixes and improvements' }}
          
          ## Installation
          1. Download the portable executable below
          2. Run the .exe file directly (no installation required)
          3. The app will automatically check for updates when launched
          
          ## Auto-Update
          The app will automatically check for updates when launched.
        files: |
          dist-electron/BrokerNet Desktop *.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

